CREATE TABLE PMS_AREABUILDING (
    PMS_AREABUILDING_ID INTEGER NOT NULL,
    NAME SHORTNAME,
    NOTE NOTE,
    SORTNUMBER SMALLINT NOT NULL);

ALTER TABLE PMS_AREABUILDING ADD PRIMARY KEY (PMS_AREABUILDING_ID);

grant select, delete, insert, update on PMS_AREABUILDING to adminrole;
grant select, delete, insert, update on PMS_AREABUILDING to premises;

CREATE GENERATOR GEN_PMS_AREABUILDING_ID;

ALTER TABLE PMS_PREMISES
ADD PMS_AREABUILDING_ID INTEGER;

CREATE TABLE PMS_EXCHANGEFORMULA (
    PMS_EXCHANGEFORMULA_ID INTEGER NOT NULL,
    NAME SHORTNAME,
    NOTE NOTE,
    SORTNUMBER SMALLINT NOT NULL);

ALTER TABLE PMS_EXCHANGEFORMULA ADD PRIMARY KEY (PMS_EXCHANGEFORMULA_ID);

grant select, delete, insert, update on PMS_EXCHANGEFORMULA to adminrole;
grant select, delete, insert, update on PMS_EXCHANGEFORMULA to premises;

CREATE GENERATOR GEN_PMS_EXCHANGEFORMULA_ID;

ALTER TABLE PMS_PREMISES
ADD PMS_EXCHANGEFORMULA_ID INTEGER;

CREATE TABLE PMS_LANDFEATURE (
    PMS_LANDFEATURE_ID INTEGER NOT NULL,
    NAME SHORTNAME,
    NOTE NOTE,
    SORTNUMBER SMALLINT NOT NULL);

ALTER TABLE PMS_LANDFEATURE ADD PRIMARY KEY (PMS_LANDFEATURE_ID);

grant select, delete, insert, update on PMS_LANDFEATURE to adminrole;
grant select, delete, insert, update on PMS_LANDFEATURE to premises;

CREATE GENERATOR GEN_PMS_LANDFEATURE_ID;

ALTER TABLE PMS_PREMISES
ADD PMS_LANDFEATURE_ID INTEGER;

CREATE TABLE PMS_LANDMARK (
    PMS_LANDMARK_ID INTEGER NOT NULL,
    NAME SHORTNAME,
    NOTE NOTE,
    SORTNUMBER SMALLINT NOT NULL);

ALTER TABLE PMS_LANDMARK ADD PRIMARY KEY (PMS_LANDMARK_ID);

grant select, delete, insert, update on PMS_LANDMARK to adminrole;
grant select, delete, insert, update on PMS_LANDMARK to premises;

CREATE GENERATOR GEN_PMS_LANDMARK_ID;

ALTER TABLE PMS_PREMISES
ADD PMS_LANDMARK_ID INTEGER;

CREATE TABLE PMS_LOCATIONSTATUS (
    PMS_LOCATIONSTATUS_ID INTEGER NOT NULL,
    NAME SHORTNAME,
    NOTE NOTE,
    SORTNUMBER SMALLINT NOT NULL);

ALTER TABLE PMS_LOCATIONSTATUS ADD PRIMARY KEY (PMS_LOCATIONSTATUS_ID);

grant select, delete, insert, update on PMS_LOCATIONSTATUS to adminrole;
grant select, delete, insert, update on PMS_LOCATIONSTATUS to premises;

CREATE GENERATOR GEN_PMS_LOCATIONSTATUS_ID;

ALTER TABLE PMS_PREMISES
ADD PMS_LOCATIONSTATUS_ID INTEGER;

CREATE TABLE PMS_POPULATEDPOINT (
    PMS_POPULATEDPOINT_ID INTEGER NOT NULL,
    NAME SHORTNAME,
    NOTE NOTE,
    SORTNUMBER SMALLINT NOT NULL);

ALTER TABLE PMS_POPULATEDPOINT ADD PRIMARY KEY (PMS_POPULATEDPOINT_ID);

grant select, delete, insert, update on PMS_POPULATEDPOINT to adminrole;
grant select, delete, insert, update on PMS_POPULATEDPOINT to premises;

CREATE GENERATOR GEN_PMS_POPULATEDPOINT_ID;

ALTER TABLE PMS_PREMISES
ADD PMS_POPULATEDPOINT_ID INTEGER;

ALTER TABLE PMS_PREMISES
ADD COMMUNICATIONS NOTE;

ALTER TABLE PMS_PREMISES
ADD EMAIL SHORTNAME;

ALTER TABLE PMS_PREMISES
ADD LEASEORSALE SHORTNAME;

ALTER TABLE PMS_PREMISES
ADD EMAIL2 SHORTNAME;

ALTER TABLE PMS_PREMISES
ADD CLIENTINFO2 SHORTNAME
COLLATE PXW_CYRL;

ALTER TABLE PMS_PREMISES
ADD CONTACT2 GUIDENAMENULL 
COLLATE PXW_CYRL 

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = NULL
where (RDB$FIELD_NAME = 'PMS_COUNTROOM_ID') and
(RDB$RELATION_NAME = 'PMS_PREMISES')











