{*******************************************************}
{                                                       }
{       Borland Delphi Visual Component Library         }
{                                                       }
{       Copyright (c) 1997,99 Inprise Corporation       }
{                                                       }
{ Руссификация: 1999 Polaris Software                   }
{               http://members.xoom.com/PolarisSoft     }
{*******************************************************}

unit mxdconst;

interface

resourcestring
  sComponentTabName      = 'Decision Cube';
  sQueryVerb0            = '&Графический построитель запросов...';
  sQueryVerb1            = 'Редактор &Decision запросов...';
  sCubeVerb0             = 'Редактор &Decision Cube...';
  sCubeVerb1             = 'Редактор &запросов...';
  sGridVerb0             = 'Под&итоги вкл/выкл';
  sSourceVerb0           = '&Не показывать пустые строки/столбцы';
  sSourceVerb1           = '&Показывать пустые строки/столбцы';
  sGridDimOptions        = 'Опции Grid Dimension';
  sGridDimSettings       = 'Настройки Grid Dimension';
  sCubeProperties        = 'Свойства Cube';

implementation

end.
