ALTER TABLE AP_AGENCY
ADD EXPORT NOTE

ALTER TABLE AP_BUILDER
ADD EXPORT NOTE

ALTER TABLE AP_COUNTROOM
ADD EXPORT NOTE

ALTER TABLE ap_field_view
ADD EXPORT NOTE

ALTER TABLE ap_home_tech
ADD EXPORT NOTE

ALTER TABLE ap_landmark
ADD EXPORT NOTE

ALTER TABLE ap_operation
ADD EXPORT NOTE

ALTER TABLE ap_planning
ADD EXPORT NOTE

ALTER TABLE ap_planning
ADD LINK NOTE

ALTER TABLE ap_region
ADD EXPORT NOTE

ALTER TABLE ap_street
ADD EXPORT NOTE

ALTER TABLE ap_style
ADD EXPORT NOTE

ALTER TABLE ap_town
ADD EXPORT NOTE

ALTER TABLE ap_type_apartment
ADD EXPORT NOTE

ALTER TABLE ap_type_balcony
ADD EXPORT NOTE

ALTER TABLE ap_type_bath
ADD EXPORT NOTE

ALTER TABLE ap_type_building
ADD EXPORT NOTE

ALTER TABLE ap_type_condition
ADD EXPORT NOTE

ALTER TABLE ap_type_door
ADD EXPORT NOTE

ALTER TABLE ap_type_furniture
ADD EXPORT NOTE

ALTER TABLE ap_type_garage
ADD EXPORT NOTE

ALTER TABLE ap_type_heat
ADD EXPORT NOTE

ALTER TABLE ap_type_internet
ADD EXPORT NOTE

ALTER TABLE ap_type_phone
ADD EXPORT NOTE

ALTER TABLE ap_type_plate
ADD EXPORT NOTE

ALTER TABLE ap_type_premises
ADD EXPORT NOTE

ALTER TABLE ap_type_sanitary
ADD EXPORT NOTE

ALTER TABLE ap_type_sewerage
ADD EXPORT NOTE

ALTER TABLE ap_type_water
ADD EXPORT NOTE


ALTER TABLE ap_unit_price
ADD EXPORT NOTE
