CREATE DOMAIN VARIANT AS
VARCHAR(1000) CHARACTER SET WIN1251
COLLATE PXW_CYRL

ALTER TABLE AP_AGENCY
ADD VARIANT VARIANT

ALTER TABLE AP_BUILDER
ADD VARIANT VARIANT

ALTER TABLE ap_countroom
ADD VARIANT VARIANT

ALTER TABLE AP_FIELD_VIEW
ADD VARIANT VARIANT

ALTER TABLE AP_HOME_TECH
ADD VARIANT VARIANT

ALTER TABLE AP_LANDMARK
ADD VARIANT VARIANT

ALTER TABLE AP_PLANNING
ADD VARIANT VARIANT

ALTER TABLE AP_REGION
ADD VARIANT VARIANT

ALTER TABLE AP_STREET
ADD VARIANT VARIANT

ALTER TABLE AP_STYLE
ADD VARIANT VARIANT

ALTER TABLE AP_TOWN
ADD VARIANT VARIANT

ALTER TABLE ap_type_apartment
ADD VARIANT VARIANT

ALTER TABLE ap_type_balcony
ADD VARIANT VARIANT

ALTER TABLE ap_type_bath
ADD VARIANT VARIANT

ALTER TABLE ap_type_building
ADD VARIANT VARIANT

ALTER TABLE ap_type_condition
ADD VARIANT VARIANT

ALTER TABLE ap_type_door
ADD VARIANT VARIANT

ALTER TABLE ap_type_furniture
ADD VARIANT VARIANT

ALTER TABLE ap_type_garage
ADD VARIANT VARIANT

ALTER TABLE ap_type_heat
ADD VARIANT VARIANT

ALTER TABLE ap_type_internet
ADD VARIANT VARIANT

ALTER TABLE ap_type_phone
ADD VARIANT VARIANT

ALTER TABLE ap_type_plate
ADD VARIANT VARIANT

ALTER TABLE ap_type_premises
ADD VARIANT VARIANT

ALTER TABLE ap_type_sanitary
ADD VARIANT VARIANT

ALTER TABLE ap_type_sewerage
ADD VARIANT VARIANT

ALTER TABLE ap_type_water
ADD VARIANT VARIANT

ALTER TABLE ap_unit_price
ADD VARIANT VARIANT


