ALTER TABLE AP_PREMISES
ADD RELEASE_ID INTEGER

ALTER TABLE AP_PREMISES
ADD FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID)

UPDATE AP_PREMISES
SET RELEASE_ID=161

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'RELEASE_ID') and
(RDB$RELATION_NAME = 'AP_PREMISES')


ALTER TABLE AP_AGENCY
ADD AP_FIELD_VIEW_ID INTEGER

ALTER TABLE AP_AGENCY
ADD FOREIGN KEY (AP_FIELD_VIEW_ID) REFERENCES AP_FIELD_VIEW (AP_FIELD_VIEW_ID)


update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = NULL
where (RDB$FIELD_NAME = 'AP_STREET_ID') and
(RDB$RELATION_NAME = 'AP_PREMISES')

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = NULL
where (RDB$FIELD_NAME = 'AP_TOWN_ID') and
(RDB$RELATION_NAME = 'AP_PREMISES')

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'WHO_INSERT_ID') and
(RDB$RELATION_NAME = 'AP_PREMISES')

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'WHEN_INSERT') and
(RDB$RELATION_NAME = 'AP_PREMISES')

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'WHO_UPDATE_ID') and
(RDB$RELATION_NAME = 'AP_PREMISES')

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'WHEN_UPDATE') and
(RDB$RELATION_NAME = 'AP_PREMISES')
