CREATE TABLE AP_REGION_STREET
(
 AP_REGION_ID INTEGER NOT NULL,
 AP_STREET_ID INTEGER NOT NULL
)

grant select, delete, insert, update, references on AP_REGION_STREET to ADMINROLE;

grant select, delete, insert, update, references on AP_REGION_STREET to PREMISES;

ALTER TABLE AP_REGION_STREET
ADD PRIMARY KEY (AP_REGION_ID,AP_STREET_ID)

ALTER TABLE AP_REGION_STREET
ADD FOREIGN KEY (AP_REGION_ID) REFERENCES AP_REGION (AP_REGION_ID)

ALTER TABLE AP_REGION_STREET
ADD FOREIGN KEY (AP_STREET_ID) REFERENCES AP_STREET (AP_STREET_ID)

ALTER TABLE AP_BUILDER
ADD PHONES NOTE

ALTER TABLE AP_BUILDER
ADD ADDRESS NOTE

ALTER TABLE AP_BUILDER
ADD SITE NOTE

ALTER TABLE AP_BUILDER
ADD EMAIL NOTE


