DROP TABLE AP_PREMISES

CREATE TABLE AP_PREMISES
(
 AP_PREMISES_ID INTEGER NOT NULL,
 AP_REGION_ID INTEGER,
 AP_LANDMARK_ID INTEGER,
 AP_TYPE_INTERNET_ID INTEGER,
 AP_TYPE_PREMISES_ID INTEGER,
 AP_STYLE_ID INTEGER,
 AP_OPERATION_ID INTEGER NOT NULL,
 AP_BUILDER_ID INTEGER,
 AP_TYPE_DOOR_ID INTEGER,
 AP_HOME_TECH_ID INTEGER,
 AP_TYPE_FURNITURE_ID INTEGER,
 AP_TYPE_GARAGE_ID INTEGER,
 AP_TYPE_BATH_ID INTEGER,
 AP_TYPE_SEWERAGE_ID INTEGER,
 AP_TYPE_CONDITION_ID INTEGER,
 AP_TYPE_PLATE_ID INTEGER,
 AP_TYPE_WATER_ID INTEGER,
 AP_TYPE_HEAT_ID INTEGER,
 WHO_INSERT_ID INTEGER,
 WHEN_INSERT TIMESTAMP,
 WHO_UPDATE_ID INTEGER,
 WHEN_UPDATE TIMESTAMP,
 DELIVERY_DATE DATE,
 NN SHORTNAME,
 AP_TOWN_ID INTEGER,
 AP_STREET_ID INTEGER,
 HOUSE SHORTNAME,
 APARTMENT SHORTNAME,
 FLOOR SHORTNAME,
 FLOOR_COUNT SHORTNAME,
 AP_TYPE_BUILDING_ID INTEGER,
 AP_COUNTROOM_ID INTEGER,
 GENERAL_AREA NUMERIC(15,2),
 DWELLING_AREA NUMERIC(15,2),
 KITCHEN_AREA NUMERIC(15,2),
 GROUND_AREA NUMERIC(15,2),
 AP_TYPE_PHONE_ID INTEGER,
 AP_TYPE_BALCONY_ID INTEGER,
 AP_PLANNING_ID INTEGER,
 AP_TYPE_APARTMENT_ID INTEGER,
 AP_TYPE_SANITARY_ID INTEGER,
 PRICE MONEY,
 AP_UNIT_PRICE_ID INTEGER,
 PHONES NOTE,
 NAME NOTE,
 AP_AGENCY_ID INTEGER NOT NULL,
 NOTE NOTE,
 PERIOD SHORTNAME,
 PAYMENT_FOR SHORTNAME,
 DELIVERY SHORTNAME
)

ALTER TABLE AP_PREMISES
ADD PRIMARY KEY (AP_PREMISES_ID)

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_LANDMARK_ID) REFERENCES AP_LANDMARK (AP_LANDMARK_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_REGION_ID) REFERENCES AP_REGION (AP_REGION_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_INTERNET_ID) REFERENCES AP_TYPE_INTERNET (AP_TYPE_INTERNET_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_PREMISES_ID) REFERENCES AP_TYPE_PREMISES (AP_TYPE_PREMISES_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_STYLE_ID) REFERENCES AP_STYLE (AP_STYLE_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_OPERATION_ID) REFERENCES AP_OPERATION (AP_OPERATION_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_BUILDER_ID) REFERENCES AP_BUILDER (AP_BUILDER_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_DOOR_ID) REFERENCES AP_TYPE_DOOR (AP_TYPE_DOOR_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_HOME_TECH_ID) REFERENCES AP_HOME_TECH (AP_HOME_TECH_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_FURNITURE_ID) REFERENCES AP_TYPE_FURNITURE (AP_TYPE_FURNITURE_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_GARAGE_ID) REFERENCES AP_TYPE_GARAGE (AP_TYPE_GARAGE_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_BATH_ID) REFERENCES AP_TYPE_BATH (AP_TYPE_BATH_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_SEWERAGE_ID) REFERENCES AP_TYPE_SEWERAGE (AP_TYPE_SEWERAGE_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_CONDITION_ID) REFERENCES AP_TYPE_CONDITION (AP_TYPE_CONDITION_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_PLATE_ID) REFERENCES AP_TYPE_PLATE (AP_TYPE_PLATE_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_WATER_ID) REFERENCES AP_TYPE_WATER (AP_TYPE_WATER_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_HEAT_ID) REFERENCES AP_TYPE_HEAT (AP_TYPE_HEAT_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (WHO_INSERT_ID) REFERENCES USERS (USER_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (WHO_UPDATE_ID) REFERENCES USERS (USER_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TOWN_ID) REFERENCES AP_TOWN (AP_TOWN_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_STREET_ID) REFERENCES AP_STREET (AP_STREET_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_BUILDING_ID) REFERENCES AP_TYPE_BUILDING (AP_TYPE_BUILDING_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_COUNTROOM_ID) REFERENCES AP_COUNTROOM (AP_COUNTROOM_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_PHONE_ID) REFERENCES AP_TYPE_PHONE (AP_TYPE_PHONE_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_BALCONY_ID) REFERENCES AP_TYPE_BALCONY (AP_TYPE_BALCONY_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_PLANNING_ID) REFERENCES AP_PLANNING (AP_PLANNING_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_APARTMENT_ID) REFERENCES AP_TYPE_APARTMENT (AP_TYPE_APARTMENT_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_TYPE_SANITARY_ID) REFERENCES AP_TYPE_SANITARY (AP_TYPE_SANITARY_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_UNIT_PRICE_ID) REFERENCES AP_UNIT_PRICE (AP_UNIT_PRICE_ID);

ALTER TABLE AP_PREMISES ADD
FOREIGN KEY (AP_AGENCY_ID) REFERENCES AP_AGENCY (AP_AGENCY_ID);

CREATE GENERATOR GEN_AP_PREMISES_ID;

DESCRIBE TABLE AP_PREMISES
'Объявления недвижимости';

grant select, delete, insert, update, references on AP_PREMISES to adminrole;
grant select, delete, insert, update on AP_PREMISES to premises;



