SELECT
P.AP_PREMISES_ID,P.AP_OPERATION_ID,P.DELIVERY_DATE,P.NN,P.PHONES AS PREMISES_PHONES,
P.NAME AS PREMISES_NAME,P.AP_TOWN_ID,P.AP_REGION_ID,P.AP_LANDMARK_ID,P.AP_STREET_ID,
P.AP_COUNTROOM_ID,P.HOUSE,P.APARTMENT,P.FLOOR,P.FLOOR_COUNT,P.AP_TYPE_BUILDING_ID,
P.GENERAL_AREA,P.DWELLING_AREA,P.KITCHEN_AREA,P.GROUND_AREA,P.NOTE,P.AP_AGENCY_ID,
P.PRICE,P.AP_UNIT_PRICE_ID,P.PERIOD,P.PAYMENT_FOR,P.DELIVERY,P.AP_TYPE_INTERNET_ID,
P.AP_TYPE_PREMISES_ID,P.AP_BUILDER_ID,P.AP_TYPE_DOOR_ID,P.AP_HOME_TECH_ID,
P.AP_TYPE_FURNITURE_ID,P.AP_TYPE_GARAGE_ID,P.AP_TYPE_BATH_ID,P.AP_TYPE_SEWERAGE_ID,
P.AP_TYPE_CONDITION_ID,P.AP_TYPE_PLATE_ID,P.AP_TYPE_WATER_ID,P.AP_TYPE_HEAT_ID,
P.AP_TYPE_PHONE_ID,P.AP_TYPE_BALCONY_ID,P.AP_PLANNING_ID,P.AP_TYPE_APARTMENT_ID,
P.AP_TYPE_SANITARY_ID,P.AP_STYLE_ID,P.WHO_INSERT_ID,P.WHEN_INSERT,P.WHO_UPDATE_ID,
P.WHEN_UPDATE,P.RELEASE_ID,T.NAME AS TOWN_NAME,S.NAME AS STREET_NAME,
R.NAME AS REGION_NAME,LM.NAME AS LANDMARK_NAME,CR.NAME AS COUNTROOM_NAME,
TB.NAME AS TYPE_BUILDING_NAME,A.NAME AS AGENCY_NAME,UP.NAME AS UNIT_PRICE_NAME,
TI.NAME AS TYPE_INTERNET_NAME,TP.NAME AS TYPE_PREMISES_NAME,B.NAME AS BUILDER_NAME,
TD.NAME AS TYPE_DOOR_NAME,HT.NAME AS HOME_TECH_NAME,TF.NAME AS TYPE_FURNITURE_NAME,
TG.NAME AS TYPE_GARAGE_NAME,TA.NAME AS TYPE_BATH_NAME,TS.NAME AS TYPE_SEWERAGE_NAME,
TC.NAME AS TYPE_CONDITION_NAME,TL.NAME AS TYPE_PLATE_NAME,TW.NAME AS TYPE_WATER_NAME,
TH.NAME AS TYPE_HEAT_NAME,TN.NAME AS TYPE_PHONE_NAME,TY.NAME AS TYPE_BALCONY_NAME,
PL.NAME AS PLANNING_NAME,TT.NAME AS TYPE_APARTMENT_NAME,TR.NAME AS TYPE_SANITARY_NAME,
ST.NAME AS STYLE_NAME,UI.NAME AS WHO_INSERT_NAME,UU.NAME AS WHO_UPDATE_NAME,
RL.ABOUT AS RELEASE_ABOUT
FROM AP_PREMISES P
JOIN USERS UI ON P.WHO_INSERT_ID=UI.USER_ID
JOIN USERS UU ON P.WHO_UPDATE_ID=UU.USER_ID
JOIN RELEASE RL ON P.RELEASE_ID=RL.RELEASE_ID
LEFT JOIN AP_TOWN T ON P.AP_TOWN_ID=T.AP_TOWN_ID
LEFT JOIN AP_STREET S ON P.AP_STREET_ID=S.AP_STREET_ID
LEFT JOIN AP_AGENCY A ON P.AP_AGENCY_ID=A.AP_AGENCY_ID
LEFT JOIN AP_REGION R ON P.AP_REGION_ID=R.AP_REGION_ID
LEFT JOIN AP_LANDMARK LM ON P.AP_LANDMARK_ID=LM.AP_LANDMARK_ID
LEFT JOIN AP_COUNTROOM CR ON P.AP_COUNTROOM_ID=CR.AP_COUNTROOM_ID
LEFT JOIN AP_TYPE_BUILDING TB ON P.AP_TYPE_BUILDING_ID=TB.AP_TYPE_BUILDING_ID
LEFT JOIN AP_UNIT_PRICE UP ON P.AP_UNIT_PRICE_ID=UP.AP_UNIT_PRICE_ID
LEFT JOIN AP_TYPE_INTERNET TI ON P.AP_TYPE_INTERNET_ID=TI.AP_TYPE_INTERNET_ID
LEFT JOIN AP_TYPE_PREMISES TP ON P.AP_TYPE_PREMISES_ID=TP.AP_TYPE_PREMISES_ID
LEFT JOIN AP_BUILDER B ON P.AP_BUILDER_ID=B.AP_BUILDER_ID
LEFT JOIN AP_TYPE_DOOR TD ON P.AP_TYPE_DOOR_ID=TD.AP_TYPE_DOOR_ID
LEFT JOIN AP_HOME_TECH HT ON P.AP_HOME_TECH_ID=HT.AP_HOME_TECH_ID
LEFT JOIN AP_TYPE_FURNITURE TF ON P.AP_TYPE_FURNITURE_ID=TF.AP_TYPE_FURNITURE_ID
LEFT JOIN AP_TYPE_GARAGE TG ON P.AP_TYPE_GARAGE_ID=TG.AP_TYPE_GARAGE_ID
LEFT JOIN AP_TYPE_BATH TA ON P.AP_TYPE_BATH_ID=TA.AP_TYPE_BATH_ID
LEFT JOIN AP_TYPE_SEWERAGE TS ON P.AP_TYPE_SEWERAGE_ID=TS.AP_TYPE_SEWERAGE_ID
LEFT JOIN AP_TYPE_CONDITION TC ON P.AP_TYPE_CONDITION_ID=TC.AP_TYPE_CONDITION_ID
LEFT JOIN AP_TYPE_PLATE TL ON P.AP_TYPE_PLATE_ID=TL.AP_TYPE_PLATE_ID
LEFT JOIN AP_TYPE_WATER TW ON P.AP_TYPE_WATER_ID=TW.AP_TYPE_WATER_ID
LEFT JOIN AP_TYPE_HEAT TH ON P.AP_TYPE_HEAT_ID=TH.AP_TYPE_HEAT_ID
LEFT JOIN AP_TYPE_PHONE TN ON P.AP_TYPE_PHONE_ID=TN.AP_TYPE_PHONE_ID
LEFT JOIN AP_TYPE_BALCONY TY ON P.AP_TYPE_BALCONY_ID=TY.AP_TYPE_BALCONY_ID
LEFT JOIN AP_PLANNING PL ON P.AP_PLANNING_ID=PL.AP_PLANNING_ID
LEFT JOIN AP_TYPE_APARTMENT TT ON P.AP_TYPE_APARTMENT_ID=TT.AP_TYPE_APARTMENT_ID
LEFT JOIN AP_TYPE_SANITARY TR ON P.AP_TYPE_SANITARY_ID=TR.AP_TYPE_SANITARY_ID
LEFT JOIN AP_STYLE ST ON P.AP_STYLE_ID=ST.AP_STYLE_ID  WHERE (P.RELEASE_ID=:RELEASE_ID)




