CREATE TABLE PMS_IMAGE (
    PMS_IMAGE_ID INTEGER NOT NULL,
    PMS_STREET_ID INTEGER NOT NULL,
    HOUSENUMBER shortname NOT NULL,
    IMAGE BLOB SUB_TYPE 1 SEGMENT SIZE 80);


ALTER TABLE PMS_IMAGE
ADD PRIMARY KEY (PMS_IMAGE_ID);

ALTER TABLE PMS_IMAGE
ADD FOREIGN KEY (PMS_STREET_ID) references PMS_STREET (PMS_STREET_ID);

CREATE GENERATOR GEN_PMS_IMAGE_ID;

SET GENERATOR GEN_PMS_IMAGE_ID TO 0;

grant select, delete, insert, update on PMS_IMAGE to adminrole

grant select, delete, insert, update on PMS_IMAGE to premises

