CREATE TABLE PMS_TAXES (
    PMS_TAXES_ID INTEGER NOT NULL,
    NAME SHORTNAME,
    NOTE NOTE,
    SORTNUMBER SMALLINT NOT NULL);

ALTER TABLE PMS_TAXES ADD PRIMARY KEY (PMS_TAXES_ID);

grant select, delete, insert, update on PMS_TAXES to adminrole;
grant select, delete, insert, update on PMS_TAXES to premises;

CREATE GENERATOR GEN_PMS_TAXES_ID;

ALTER TABLE PMS_PREMISES
ADD PMS_TAXES_ID INTEGER;

