CREATE TABLE PMS_ADVERTISMENT (
    PMS_ADVERTISMENT_ID INTEGER NOT NULL,
    NAME SHORTNAME,
    NOTE NOTE,
    AMOUNT INTEGER NOT NULL);


ALTER TABLE PMS_ADVERTISMENT ADD PRIMARY KEY (PMS_ADVERTISMENT_ID);


CREATE TABLE PMS_PREMISES_ADVERTISMENT (
    PMS_ADVERTISMENT_ID INTEGER NOT NULL,
    PMS_PREMISES_ID INTEGER NOT NULL,
    PMS_AGENT_ID INTEGER NOT NULL);


ALTER TABLE PMS_PREMISES_ADVERTISMENT ADD PRIMARY KEY (PMS_ADVERTISMENT_ID, PMS_PREMISES_ID, PMS_AGENT_ID);

ALTER TABLE PMS_PREMISES_ADVERTISMENT ADD FOREIGN KEY (PMS_ADVERTISMENT_ID) REFERENCES PMS_ADVERTISMENT (PMS_ADVERTISMENT_ID)

ALTER TABLE PMS_PREMISES_ADVERTISMENT ADD FOREIGN KEY (PMS_PREMISES_ID,PMS_AGENT_ID) REFERENCES PMS_PREMISES(PMS_PREMISES_ID,PMS_AGENT_ID)


grant select, delete, insert, update on PMS_ADVERTISMENT to adminrole

grant select, delete, insert, update on PMS_ADVERTISMENT to premises

grant select, delete, insert, update on PMS_PREMISES_ADVERTISMENT to adminrole

grant select, delete, insert, update on PMS_PREMISES_ADVERTISMENT to premises

CREATE GENERATOR GEN_PMS_ADVERTISMENT_ID;
SET GENERATOR GEN_PMS_ADVERTISMENT_ID TO 3;
